[package]
name = "classmate"
version = "0.5.0"
rust-version = "1.61"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.3"
parcel_css = "1.0.0-alpha.29"
owning_ref = "0.4"
tap = "1.0"
smallvec = "1.8"
