
name: CI
on: push

jobs:
  specs:
    name: Specs
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          rubygems: latest
          bundler-cache: true

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ext/classmate

      - name: Compile native extension
        run: bundle exec rake compile

      - name: Run specs
        run: bundle exec rspec --format documentation

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61
          components: clippy
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ext/classmate

      - name: Run Clippy
        run: cd ext/classmate && cargo clippy --no-deps
