name: Release
on: workflow_dispatch

jobs:
  gem-build:
    name: Gem build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          rubygems: latest
          bundler-cache: true

      - name: Build source gem
        run: bundle exec rake build

      - name: Build native gems
        run: bundle exec rake gem:native

      - name: Upload built gems
        uses: actions/upload-artifact@v3
        with:
          name: gems
          path: pkg/*.gem
